FROM python:3.9-slim

WORKDIR /app

COPY ui_requirements.txt .
RUN pip install --no-cache-dir -r ui_requirements.txt

COPY app.py .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]